android.useAndroidX=true
org.gradle.caching=true
dependency.analysis.compatibility=NONE
org.gradle.jvmargs=-Xlog:gc*:file=/home/runner/work/Telltale/Telltale/gradle_gc.log -Xmx6g -XX:+HeapDumpOnOutOfMemoryError -Dfile.encoding=UTF-8  -XX:MaxMetaspaceSize=1g
kotlin.daemon.jvmargs=-Xlog:gc*:file=/home/runner/work/Telltale/Telltale/kotlin_gc.log -Dfile.encoding=UTF-8 -Xmx5g -XX:MaxMetaspaceSize=1g
kotlin.build.report.output=build_scan